language: java
sudo: false
jdk:
  - oraclejdk8
services:
    - mongodb
sudo: required
before_install:
 - chmod +x mvnw
before_script:
  - pip install --user codecov
after_success:
  - codecov
branches:
  only:
  - master
cache:
  directories:
  - .autoconf
  - $HOME/.m2
install: true